home : /home/BCCRC.CA/ssubedi/projects/tumour_immune_interaction/
database : database/
input : input/pbmc/
output : output/pbmc/
scanpy_output : output/pbmc/scanpy/

immune_signature_genes : PanglaoDB_markers_27_Mar_2020.tsv
lr_db : celltalkdb_v20220131_human_lr_pair.txt


raw_data_scpy : 'filtered_gene_bc_matrices/hg19/'
raw_data : PBMC.counts.FILTERED.counts.pkl
raw_data_genes : PBMC.counts.FILTERED.GENES.pkl
raw_data_no_lr_genes : PBMC.counts.FILTERED.GENES_noLR.pkl
raw_l_data : PBMC.counts.FILTERED.counts.ligands.pkl
raw_l_data_genes : PBMC.counts.FILTERED.GENES.ligands.pkl
raw_r_data : PBMC.counts.FILTERED.counts.receptors.pkl
raw_r_data_genes : PBMC.counts.FILTERED.GENES.receptors.pkl
raw_lr_data : PBMC.counts.FILTERED.counts.ligands_receptors_mat_815_780.pkl


nbr_model : 
  sparse_data : PBMC_coo_matrix_no_lr.npz
  sparse_label : PBMC_label_no_lr.npz
  sparse_immune_label : PBMC_label_immune_index_no_lr.npz
  in : input/pbmc/
  out : model/nbr_net/
  train :
    batch_size : 128
    l_rate : 0.01
    epochs : 200
    layers1 : [200,200,100,15]
    layers2 : [200,200,100,15]
    latent_dims : 15
  eval :
    batch_size : 2700
  mfile : pbmc_200_200_100_15_ep2500_no_lr_202204142214

lr_model : 
  out : model/lr_net/
  in : lr_tensor/
  train :
    nbr_size : 4
    batch_size : 5
    l_rate : 0.01
    epochs : 2
    layers1 : [200,100,50]
    layers2 : [200,100,50]
    latent_dims : 50
    input_dims1 : 380
    input_dims2 : 302
  eval :
    batch_size : 1
  mfile : pbmc_200_200_100_50_ep2500_no_lr_lrnet_202204142214_202204190521

