home : /tumour_immune_interaction/
database : database/
input : input/
output : output/

metadata : GSE156728_metadata.txt.gz
protein_coding_genes : homo_sapiens.grch38.104.protein_coding_genes.txt
immune_signature_genes : ImmuCellDB_signature_genes.txt
lr_db : celltalkdb_v20220131_human_lr_pair.txt
tcell_signature_genes : science.abe6474_table_s3.xlsx


raw_data : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_17k.pkl
raw_data_genes : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_17k_GENES.pkl
raw_data_no_lr_genes : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_17k_GENES_noLR.pkl
raw_l_data : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_17k.ligands.pkl
raw_l_data_genes : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_17k_GENES.ligands.pkl
raw_r_data : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_17k.receptors.pkl
raw_r_data_genes : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_17k_GENES.receptors.pkl
raw_lr_data : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_17k.ligands_receptors_mat_815_780.pkl

sample_first : GSE156728_BC_10X.CD4.counts.txt.gz
samples : 
  - GSE156728_BC_10X.CD4.counts.txt.gz
  - GSE156728_BCL_10X.CD4.counts.txt.gz
  - GSE156728_ESCA_10X.CD4.counts.txt.gz
  - GSE156728_MM_10X.CD4.counts.txt.gz
  - GSE156728_PACA_10X.CD4.counts.txt.gz
  - GSE156728_RC_10X.CD4.counts.txt.gz
  - GSE156728_THCA_10X.CD4.counts.txt.gz
  - GSE156728_UCEC_10X.CD4.counts.txt.gz
  - GSE156728_BC_10X.CD8.counts.txt.gz
  - GSE156728_BCL_10X.CD8.counts.txt.gz
  - GSE156728_ESCA_10X.CD8.counts.txt.gz
  - GSE156728_MM_10X.CD8.counts.txt.gz
  - GSE156728_PACA_10X.CD8.counts.txt.gz
  - GSE156728_RC_10X.CD8.counts.txt.gz
  - GSE156728_THCA_10X.CD8.counts.txt.gz
  - GSE156728_UCEC_10X.CD8.counts.txt.gz

nbr_model : 
  sparse_data : GSE156728_coo_matrix_no_lr_180k_17k.npz
  sparse_label : GSE156728_label_no_lr_180k_17k.npz
  sparse_immune_label : GSE156728_label_immune_index_no_lr_180k_17k.npz
  in : tcell_source/
  out : model/nbr_net/
  train :
    batch_size : 128
    l_rate : 0.01
    epochs : 2500
    layers1 : [200,200,100,15]
    layers2 : [200,200,100,15]
    latent_dims : 15
  eval :
    batch_size : 178000
  mfile : 200_200_100_25_ep2500_180k_17k_no_lr_202204081557

lr_model : 
  out : model/lr_net/
  in : lr_tensor/
  in_nbr_model : 200_200_100_15_ep2500_180k_17k_no_lr_202204081556etm_hh_data.tsv
  train :
    nbr_size : 5
    batch_size : 256
    run_batch_size : 1
    l_rate : 0.01
    epochs : 2500
    layers1 : [200,100,50]
    layers2 : [200,100,50]
    latent_dims : 50
  eval :
    batch_size : 1
  mfile : 200_200_100_50_ep2500_180k_17k_no_lr_202204081556202204100530

