home : /home/BCCRC.CA/ssubedi/projects/tumour_immune_interaction/
database : database/
pscripts : scmetm/
rscripts : R


metadata : GSE156728_metadata.txt.gz
protein_coding_genes : homo_sapiens.grch38.104.protein_coding_genes.txt
immune_signature_genes : ImmuCellDB_signature_genes.txt
lr_db : celltalkdb_v20220131_human_lr_pair.txt

input : input/
output : output/

raw_data : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_18k.pkl
raw_genes : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_18k_GENES.pkl
lr_bimat : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_18k.ligands_receptors_mat_815_780.pkl


sample_first : GSE156728_BC_10X.CD4.counts.txt.gz
samples : 
  - GSE156728_BC_10X.CD4.counts.txt.gz
  - GSE156728_BCL_10X.CD4.counts.txt.gz
  - GSE156728_ESCA_10X.CD4.counts.txt.gz
  - GSE156728_MM_10X.CD4.counts.txt.gz
  - GSE156728_PACA_10X.CD4.counts.txt.gz
  - GSE156728_RC_10X.CD4.counts.txt.gz
  - GSE156728_THCA_10X.CD4.counts.txt.gz
  - GSE156728_UCEC_10X.CD4.counts.txt.gz
  - GSE156728_BC_10X.CD8.counts.txt.gz
  - GSE156728_BCL_10X.CD8.counts.txt.gz
  - GSE156728_ESCA_10X.CD8.counts.txt.gz
  - GSE156728_MM_10X.CD8.counts.txt.gz
  - GSE156728_PACA_10X.CD8.counts.txt.gz
  - GSE156728_RC_10X.CD8.counts.txt.gz
  - GSE156728_THCA_10X.CD8.counts.txt.gz
  - GSE156728_UCEC_10X.CD8.counts.txt.gz

nbr_model : 
  sparse_data : GSE156728_coo_matrix_
  sparse_label : GSE156728_label_
  data_tag : 180k_18k
  out : model/nbr_net/
  train :
    batch_size : 64
    l_rate : 0.001
    epochs : 1000
    layers1 : [128,128,1000,32,16]
    layers2 : [128,128,1000,32,16]
    latent_dims : 16
  eval :
    batch_size : 178000
  mfile : 128_128_1000_32_16_ep1000_tcells_180k_18k_

lr_model : 
  l_data : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_18k.ligands.pkl
  r_data : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_18k.receptors.pkl
  lr_data : GSE156728_ALLTISSUE_10X.CD4.CD8.counts.FILTERED.180k_18k.ligands_receptors_mat_815_780.pkl
  data_tag : lr_net
  out : model/lr_net/
  train :
    nbr_size : 50
    batch_size : 128
    l_rate : 0.01
    epochs : 100
    layers1 : [128,512,64]
    layers2 : [128,512,64]
    latent_dims : 64
  eval :
    batch_size : 100
  mfile : 128_128_1000_128_ep100_lrnet_





